In [1]:
import torch
import torch.nn as nn

In [2]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)
torch.cuda.get_device_name(0)

cuda


'GeForce GTX 1050 Ti'

In [17]:
a = torch.rand(6,5)
b = torch.rand(2,5)
print(a)
print(b)

tensor([[0.3733, 0.8560, 0.6473, 0.0516, 0.9855],
        [0.1496, 0.4359, 0.9715, 0.1437, 0.5936],
        [0.0833, 0.6469, 0.9967, 0.9767, 0.5264],
        [0.3079, 0.6506, 0.0037, 0.7094, 0.0754],
        [0.3508, 0.4714, 0.0400, 0.4489, 0.7577],
        [0.8732, 0.5494, 0.9489, 0.1657, 0.4292]])
tensor([[0.1047, 0.4219, 0.0421, 0.5113, 0.2196],
        [0.4309, 0.0453, 0.9427, 0.6698, 0.9018]])


In [21]:
target = torch.zeros(6, 5)
target[:2, :] = b
target

tensor([[0.1047, 0.4219, 0.0421, 0.5113, 0.2196],
        [0.4309, 0.0453, 0.9427, 0.6698, 0.9018],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000]])